//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rina.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rina.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   _  _______ _______    _____ _____ _  ____  __      __     __        ____           _____ _           __     __      ____ _____ _      _____ _____   _____ _____ _   _ 
        /// | |/ /  __ \__   __|  / ____|_   _| |/ /  \/  |   /\\ \   / //\     |  _ \   /\    / ____| |        /\\ \   / //\   |  _ \_   _| |    |_   _|  __ \ / ____|_   _| \ | |
        /// | &apos; /| |  | | | |    | (___   | | | &apos; /| \  / |  /  \\ \_/ //  \    | |_) | /  \  | (___ | |       /  \\ \_/ //  \  | |_) || | | |      | | | |__) | (___   | | |  \| |
        /// | [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KDT {
            get {
                return ResourceManager.GetString("KDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JALE
        ///ALİ
        ///MAHMUT
        ///MANSUR KÜRŞAD
        ///GAMZE
        ///MİRAÇ
        ///YÜCEL
        ///KUBİLAY
        ///HAYATİ
        ///BEDRİYE MÜGE
        ///BİRSEN
        ///SERDAL
        ///BÜNYAMİN
        ///ÖZGÜR
        ///FERDİ
        ///REYHAN
        ///İLHAN
        ///GÜLŞAH
        ///NALAN
        ///SEMİH
        ///ERGÜN
        ///FATİH
        ///ŞENAY
        ///SERKAN
        ///EMRE
        ///BAHATTİN
        ///IRAZCA
        ///HATİCE
        ///BARIŞ
        ///REZAN
        ///FATİH
        ///FUAT
        ///GÖKHAN
        ///ORHAN
        ///MEHMET
        ///EVREN
        ///OKTAY
        ///HARUN
        ///YAVUZ
        ///PINAR
        ///MEHMET
        ///UMUT
        ///MESUDE
        ///HÜSEYİN CAHİT
        ///HAŞİM ONUR
        ///EYYUP SABRİ
        ///MUSTAFA
        ///MUSTAFA
        ///UFUK
        ///AHMET ALİ
        ///MEDİHA
        ///HASAN
        ///KAMİL
        ///NEBİ
        ///ÖZCAN
        ///NAGİHAN
        ///CEREN
        ///SERKAN
        ///HASAN
        ///YUSUF KENAN
        ///ÇETİN
        ///TARKAN
        ///MERAL LEMAN        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string names {
            get {
                return ResourceManager.GetString("names", resourceCulture);
            }
        }
    }
}
